# Generated by Django 3.2.8 on 2021-10-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_auto_20211030_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='case',
            field=models.CharField(blank=True, choices=[('first_time', 'First_time'), ('edit', 'Edit')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='craftman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='qc.profile'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='qc.profile'),
        ),
    ]
