# Generated by Django 3.2.8 on 2021-10-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_auto_20211030_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='craftman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftman', to='qc.profile'),
        ),
    ]
