# Generated by Django 3.2.8 on 2021-10-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0006_auto_20211030_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchecklist',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
