# Generated by Django 3.2.8 on 2021-10-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_orderchecklist_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('sended', 'Sended')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.workorder')),
            ],
            options={
                'db_table': 'message_orders',
            },
        ),
    ]
